### ISSUE TITLE
Confusing colours

### ISSUE THREAD

**Issue by henrydtheodo** [spencermehta/wizzdle#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

<img width="586" alt="image" src="https://user-images.githubusercontent.com/90182308/155691579-e1923b36-dbbb-4eb2-86d5-521fbcef2085.png">

**Comment by spencermehta** [comment]
Hi @henrydtheodo, thanks for raising!

I've pushed a fix for this. The issue was it was displaying the colors for the first 3 characters on the last 3 characters too.
